### ISSUE TITLE
My actual roadmap with uLaunch

### ISSUE THREAD

**Issue by Simi5599** [Simi5599/uLaunch#1]
Features and fixes to be implemented:

- [ ] Fix timezones (Currently the time is displayed in UTC only)
- [ ] Create a loop with the titles (Like the OG switch UI, moving after the last item brings me back to the first item)
- [ ] Implement Italian language
- [x] Do not close the quick menu whenreturning from a submenu (For example if i open the power options and then i select "Cancel" i don't want to quit the quick menu
- [ ] Add SFX when launching something from the quick menu
- [ ] Add SFX when selecting something from g_MenuApplication->CreateShowDialog();
- [ ] Add SFX when closing g_MenuApplication->CreateShowDialog();
- [ ] Add a Mii functionality on the quick menu
- [ ] Support animated wallpapers (GIF)
- [ ] Fix performance issues
- [ ] Support Bt headphones (i don't know if i can implement this functionality)

Need also to update the theming docs and the README after every UI change
